# Badges Block Demo - Partner/certification badges
[config]
lang = "en"
url = "/blocks/badges"
menu = "Badges"
collection = "blocks"

[meta]
title = "Badges Block â€” Blocks Library"
description = "Partner and certification badges with ratings."

[badges]
tag = "badges"
title = "Certified & Recognized"

[[badges.badges]]
name = "Clutch"
rating = 4.9
reviews = "18 Reviews"
url = "https://clutch.co"

[[badges.badges]]
name = "Google Partner"
icon = "award"
label = "Certified Partner"

[[badges.badges]]
name = "GoodFirms"
rating = 4.8
reviews = "12 Reviews"
url = "https://goodfirms.co"

[[badges.badges]]
name = "UpCity"
rating = 5.0
reviews = "8 Reviews"
