# Bloglist Block Demo
[config]
lang = "en"
url = "/blocks/bloglist"
menu = "Blog List"
collection = "blocks"

[meta]
title = "Blog List Block â€” Blocks Library"
description = "Display a list of blog articles."

[bloglist]
tag = "bloglist"
title = "Blog Article Listing"
show_featured = true
show_categories = true
